Task_1_1_2
Anqeliccom/OOP pull request #2
Opened 2024-09-15 18:20 UTC by Anqeliccom

2024-09-16 11:41 UTC, Sharapov-Maksim requested changes
Хорошая работа, доделывайте, мягкий дедлайн зачтён

2024-09-16 11:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/BlackjackGame.java
> +            if ("0".equals(input)) {
А что будет, если пользователь введёт `0    `, или что угодно, кроме `0` и `1`? Нужно как-нибудь более дружелюбно к пользователю обработать ввод, сообщать ему об ошибке / предложить ввести ещё раз

2024-09-16 11:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +        String[] ranks = {
Массивы `ranks` и `values` очень сильно связаны между собой логически. Есть инвариант, что эти массивы должны быть одинакого размера. Однако ни эта логическая связь, ни инвариант, напрямую не выражены в коде.

Предлагаю применить объектный подход и связать эти пары строка - значение с помошью объектов

2024-09-16 11:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +public class BlackjackGameTest {
Тесты на функциональность разных классов принято оформлять в разных тестовых классах (`CardTest`, `DeckTest` и т.д.)

2024-09-16 11:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +        String[] suits = {
В целом, все эти три массива могли быть статическими, нет нужды создавать их каждый раз в конструкторе `Deck`

2024-09-20 15:33 UTC, Anqeliccom commented on Task_1_1_2/src/main/java/org/example/BlackjackGame.java
> +            if ("0".equals(input)) {
fixed

2024-09-20 15:33 UTC, Anqeliccom commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +        String[] ranks = {
fixed

2024-09-20 15:33 UTC, Anqeliccom commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +public class BlackjackGameTest {
fixed

2024-09-20 15:33 UTC, Anqeliccom commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +        String[] suits = {
fixed

2024-09-20 15:37 UTC, Anqeliccom commented
Запрос очередной итерации ревью.

2024-09-22 08:03 UTC, Sharapov-Maksim requested changes
Правки выдал, не забудьте поправить замечания checkstyle

2024-09-22 08:03 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/BlackjackGame.java
> +        if (player.getScore() == 21 && dealer.getScore() == 21) {
Константа 21 имеет специфический смысл и употребляется несколько раз, очень хороший повод дать ей имя

2024-09-22 08:03 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +public class BlackjackGameTest {
А давайте сделаем тесты на разные игровые сценарии по аналогии с `testDeckReshufflesWhenLessThan13Cards`, когда игрок всегда берёт карты или всегда не берёт, а в конце таких тестов проверки на то, что `Game` находится в ожидаемом состоянии

2024-09-22 08:03 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Card.java
> +    public String toString() {
метод нигде не используется, кроме тестов, или я не нашёл

2024-09-22 08:03 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/example/DeckTest.java
> +public class DeckTest {
Тест на опустошение колоды добавить бы

2024-09-22 12:29 UTC, Anqeliccom commented on Task_1_1_2/src/main/java/org/example/BlackjackGame.java
> +        if (player.getScore() == 21 && dealer.getScore() == 21) {
fixed

2024-09-22 12:31 UTC, Anqeliccom commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +public class BlackjackGameTest {
fixed

2024-09-22 12:32 UTC, Anqeliccom commented on Task_1_1_2/src/main/java/org/example/Card.java
> +    public String toString() {
Да, он действительно использовался только в тесте (видимо, забыла удалить). Метод и тест удалены

2024-09-22 12:36 UTC, Anqeliccom commented on Task_1_1_2/src/test/java/org/example/DeckTest.java
> +public class DeckTest {
Зачем? Такой тест уже есть в файле BlackjackGameTest.java. Или речь про другое опустошение?

2024-09-22 12:38 UTC, Anqeliccom commented
Запрос очередной итерации ревью.

2024-09-22 14:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +        assertTrue(game.getDeck().getCards().size() >= 41);
А может ещё какие-то условия возможно проверить? Например, что после этого раунда кто-то победил, изменился счёт

2024-09-22 14:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/example/DeckTest.java
> +public class DeckTest {
А, у вас она потом пополняется при опустошении, ладно. Я упустил тест, который вы упомянули

2024-09-22 14:32 UTC, Sharapov-Maksim requested changes
Осталось чуть чуть =)

2024-09-23 08:19 UTC, Anqeliccom commented on Task_1_1_2/src/test/java/org/example/BlackjackGameTest.java
> +        assertTrue(game.getDeck().getCards().size() >= 41);
fixed

2024-09-23 08:24 UTC, Anqeliccom commented
Запрос очередной итерации ревью :'-)

2024-09-23 09:58 UTC, Sharapov-Maksim approved these changes
Замечания исправлены

2024-09-23 09:59 UTC, Sharapov-Maksim commented
Задание засчитано, можно мёржить

2024-09-23 15:49 UTC, merged