Task_1_1_3
Anqeliccom/OOP pull request #3
Opened 2024-09-29 02:51 UTC by Anqeliccom

2024-09-29 04:14 UTC, Anqeliccom commented
Запрос первой итерации ревью решения с доп заданием.

2024-09-29 12:51 UTC, Sharapov-Maksim requested changes
Хорошая работа, мягкий дедлайн зачтён, доделывайте

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Mul.java
> +        if (simplifiedLeft.print().equals("0") || simplifiedRight.print().equals("0")) {
Давайте вместо сравнения строк воспользуемся `equals(new Number(0))` и аналогично во всех таких местах

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expression.java
> +    public abstract String print();
Будет лучше переименовать во что-нибудь на подобие `toString`. У вас ведь фактически реализации ничего не печатают, а только возвращают строковое представление

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expression.java
> +public abstract class Expression {
Не забудьте javadoc ко всем публичным методам

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/org/example/ExpressionTest.java
> +        assertEquals("(x+5)", expr.print());
Давайте не только строки сравнивать, но и объекты. Т.е. в качестве ожидаемого объекта самостоятельно сконструировать выражение, а потом сравнить с полученным. Переопределённый `equals` это позволит сделать

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/org/example/DivTest.java
> +class DivTest {
Стоит и деление на ноль проверить, что нужное исключение выбрасывается

2024-09-29 12:51 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/org/example/SubTest.java
> +        assertEquals(0, simplified.eval(""));
Такие места можно заменить на
```
assertEquals(new Number(0), simplified);
```

2024-10-06 04:16 UTC, Anqeliccom commented on Task_1_1_3/src/main/java/org/example/Mul.java
> +        if (simplifiedLeft.print().equals("0") || simplifiedRight.print().equals("0")) {
fixed

2024-10-06 04:16 UTC, Anqeliccom commented on Task_1_1_3/src/main/java/org/example/Expression.java
> +    public abstract String print();
fixed

2024-10-06 04:16 UTC, Anqeliccom commented on Task_1_1_3/src/main/java/org/example/Expression.java
> +public abstract class Expression {
fixed

2024-10-06 04:19 UTC, Anqeliccom commented on Task_1_1_3/src/test/java/org/example/ExpressionTest.java
> +        assertEquals("(x+5)", expr.print());
fixed

2024-10-06 04:20 UTC, Anqeliccom commented on Task_1_1_3/src/test/java/org/example/DivTest.java
> +class DivTest {
Деление на ноль проверяется в testEvalDivideByZero() (файл ExpressionTest.java)

2024-10-06 04:21 UTC, Anqeliccom commented on Task_1_1_3/src/test/java/org/example/SubTest.java
> +        assertEquals(0, simplified.eval(""));
fixed

2024-10-06 04:23 UTC, Anqeliccom commented
Запрос очередной итерации ревью (с доп заданиями-были и в мягком дедлайне)

2024-10-06 11:14 UTC, Sharapov-Maksim approved these changes
Задача засчитана, доп. баллы: 2

PR можно мёржить

2024-10-06 11:58 UTC, merged