Task_1_2_1
Anqeliccom/OOP pull request #4
Opened 2024-10-30 04:18 UTC by Anqeliccom

2024-10-30 08:05 UTC, Sharapov-Maksim requested changes
Хорошая работа, доделывайте. Мягкий дедлайн зачтён

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/AdjacencyList.java
> +    }
Получается `addVertex` не зависит от аргумента? Вы тут либо возвращайте выделенный индекс, либо используйте

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/AdjacencyMatrix.java
> +    }
Аналогично, что-то с аргументом надо придумать

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/Graph.java
> +    void removeEdge(int from, int to);
Когда будете описывать, не забудьте описать краевые случаи, и чтобы реализации соответствовали описанию

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/AdjacencyList.java
> +    }
Тесты нужны более сложные

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/AbstractGraph.java
> +    }
Ваш `hascode` удовлетворяет этому свойству?
> If two objects are equal according to the equals method, then calling the hashCode method on each of the two objects must produce the same integer result.

Особенно в контексте разных представлений одного и того же графа.

Мне кажется что хеш зависит от порядка элементов в `getNeighbors`, он пока что у вас не специфицирован. Может сделать `Set`?

2024-10-30 08:05 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/AbstractGraph.java
> +            }
Тут тоже получается, что равенство от порядка зависит. Если так и должно быть, то надо описать в `getNeighbors`

2024-11-04 16:17 UTC, Anqeliccom commented
Запрос очередной итерации ревью.

2024-11-04 16:18 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/AdjacencyList.java
> +    }
fixed

2024-11-04 16:18 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/AdjacencyMatrix.java
> +    }
fixed

2024-11-04 16:18 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/Graph.java
> +    void removeEdge(int from, int to);
fixed

2024-11-04 16:18 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/AbstractGraph.java
> +    }
fixed

2024-11-04 16:18 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/AbstractGraph.java
> +            }
fixed

2024-11-04 17:07 UTC, Sharapov-Maksim requested changes

2024-11-04 17:07 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/Graph.java
>  public interface Graph {
Давайте `equals` и `hashcode` в интерфейсе задекларируем, чтобы обязать всех наследников `Graph` следовать описанию из javadoc, а не только наследников `AbstractGraph`

2024-11-04 17:07 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/Graph.java
>  public interface Graph {
Расскажите, как добавить в имеющуюся объектную модель новый способ представления графа?

2024-11-05 02:31 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/Graph.java
>  public interface Graph {
fixed

2024-11-05 02:37 UTC, Anqeliccom commented on Task_1_2_1/src/main/java/org/example/Graph.java
>  public interface Graph {
Нужно создать новый класс для представления графа, унаследовать его от AbstractGraph,  реализовать в нем все методы интерфейса Graph, кроме тех, что реализованы в AbstractGraph

2024-11-05 02:39 UTC, Anqeliccom commented
Запрос очередной итерации ревью.

2024-11-05 04:10 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/Graph.java
>  public interface Graph {
Дополню: _... или отнаследовать сразу от интерфейса `Graph`_

2024-11-05 04:10 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-05 04:47 UTC, merged