Task_1_3_1
Anqeliccom/OOP pull request #5
Opened 2024-11-11 15:15 UTC by Anqeliccom

2024-11-11 15:24 UTC, Anqeliccom commented
Запрос первой итерации ревью.

2024-11-11 18:01 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён

2024-11-11 18:01 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/org/example/SearchSubstringTest.java
> +        generateRepeatedStringFile(filename, substring, repeatCount);
> большие данные, необходимые только для тестирования, не нужно добавлять в систему контроля версий, их нужно генерировать в процессе тестирования.

2024-11-11 18:01 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/org/example/SearchSubstringTest.java
> +class SearchSubstringTest {
> размер входного файла может быть во много раз больше объема оперативной памяти вычислительного устройства, а размер искомой подстроки — во много раз меньше;

Давайте подобный тест добавите, где файл в несколько раз больше свободной памяти под кучу. 
И попробуйте провести эксперимент: запустить данный тест с ограниченным размером кучи (см. -Xmx VM option, например: `-Xmx256m` для файла в 1GB. Или `maxHeapSize = '256m'` в `build.gradle`), проверить, что он не падает с OutOfMemory. При этом стоит сделать тест так, чтобы не раздувать список `occurences`, желательно чтобы найденное вхождение было одно или их не было вовсе. Об условиях и результатах эксперимента напишите комментарий =)

2024-11-11 18:01 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/org/example/SearchSubstring.java
> +    }
Решили простым квадратичным алгоритмом обойтись? Настаивать на эффективном алгоритме не буду, но с таким могут возникнуть проблемы с большими файлами...

2024-11-17 18:07 UTC, Anqeliccom commented on Task_1_3_1/src/main/java/org/example/SearchSubstring.java
> +    }
fixed

2024-11-17 18:07 UTC, Anqeliccom commented on Task_1_3_1/src/test/java/org/example/SearchSubstringTest.java
> +        generateRepeatedStringFile(filename, substring, repeatCount);
fixed

2024-11-17 18:24 UTC, Anqeliccom commented on Task_1_3_1/src/test/java/org/example/SearchSubstringTest.java
> +class SearchSubstringTest {
добавлен testLimitedHeapMemory, в котором:
- создается файл размер 1 ГБ + размер искомой строки(9 байт);
- проверяется индекс вхождения строки;
- проверяется непревышение максимума используемой памяти(256 МБ);     
                                                                         
в build.gradle добавлено соответсвующее ограничение: maxHeapSize = "256m"
после запуска тест не падает с OutOfMemory и выводит:

![изображение](https://github.com/user-attachments/assets/3c5869f0-9ddb-41ce-89e0-c08b6c09eccf)

2024-11-17 18:29 UTC, Anqeliccom commented
Запрос очередной итерации ревью.

2024-11-18 06:28 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-18 06:51 UTC, merged